### PR TITLE
added a chart with a date range picker

### PR DESCRIPTION
**Pull request by anatolzak**
https://github.com/lingster/drf-api-tracking/issues/10

added a chart to display the number of logs per day. there is also the ability to change the dates of the chart via a date range picker

image

=================================

image

### CODE REVIEW

**Comment by anatolzak** [comment]
Hi @lingster.

Is my pull request being considered? I am using this package and would love to see the charts added to the package just as you wanted as well since you opened this issue https://github.com/lingster/drf-api-tracking/issues/10. 

I would appreciate it if you consider this pull request.

Thank you.

**Comment by lingster** [comment]
@anatolzak : nice work with the charts! There seems to be a merge conflict pending, can you check and then I will be able to review and merge accordingly...

**Comment by anatolzak** [comment]
@lingster I fixed the merge conflict. Thank you for considering my pull request.

**Comment by anatolzak** [comment]
Hi @lingster, have you reviewed my pull request? Thank you

**Pull request merged**
